name: Code formatting checks
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  python-black:
    name: Format code with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run black formatter checks
        uses: psf/black@stable
        with:
          src: "./backend"
          options: "--check --diff --color"
          jupyter: true
